package es.progcipfpbatoi.batoiflix_prg.model.entities;


/*
 * public enum Genero {
    ACCION,FANTASIA,MUSICAL,HISTORIA,DEPORTES,BIOGRAFIA,COMEDIA,
    CIENCIA_FICCION,MISTERIO,OESTE,TERROR,FAMILIAR,ROMANTICAS,SUSPENSE,AVENTURAS,CRIMENES,DRAMA,ANIMACION
}
 */


public enum Genero {
    ACTION, FANTASY, MUSICAL, HISTORY, SPORTS, BIOGRAPHY, COMEDY,
    SCI_FI, MYSTERY, WESTERN, HORROR, FAMILY, ROMANCE, THRILLER,
    ADVENTURE, CRIME, DRAMA, ANIMATION
}
